sudo: false

language: scala

scala:
  - 2.11.11
  - 2.12.2

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls
  - "[[ $TRAVIS_BRANCH == \"master\" ]] && { sbt publish; };"

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

