sudo: false
language: scala
scala:
- 2.11.11
- 2.12.2
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sbt"
  - "$HOME/.ivy2"
script:
- sbt ++$TRAVIS_SCALA_VERSION clean coverage scalafmtTest test
after_success:
- sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls
- '[[ "$TRAVIS_BRANCH" = "master" -o "$TRAVIS_TAG" =~ ^v[0-9]+\.[0-9]+(\.[0-9]+)?(-[A-Za-z0-9-]+)? ]] && [ "$TRAVIS_PULL_REQUEST" = "false" ] && echo "Publishing Release $TRAVIS_BRANCH:$TRAVIS_TAG" && tar xf secrets.tar && mkdir ~/.bintray && cp publishing/.credentials ~/.bintray/ && cp publishing/.artifactory ~/.bintray/ && sbt publish'
before_cache:
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete
before_install:
- openssl aes-256-cbc -K $encrypted_09ef3e55c311_key -iv $encrypted_09ef3e55c311_iv
  -in secrets.tar.enc -out secrets.tar -d
